<?php
session_start();
include("db.php");

$error = "";
$username = "";

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = trim($_POST['username']);
        $password = trim($_POST['password']);
            
                $sql = "SELECT * FROM users WHERE username=? LIMIT 1";
                    $stmt = $conn->prepare($sql);
                        $stmt->bind_param("s", $username);
                            $stmt->execute();
                                $result = $stmt->get_result();
                                    
                                        if ($result->num_rows === 1) {
                                                $row = $result->fetch_assoc();
                                                        if (password_verify($password, $row['password'])) {
                                                                    $_SESSION['username'] = $row['username'];
                                                                                header("Location: index.php");
                                                                                            exit();
                                                                                                    }
                                                                                                        }
                                                                                                            $error = "Kullanıcı adı veya şifre hatalı!";
                                                                                                            }
                                                                                                            ?>
                                                                                                            <!DOCTYPE html>
                                                                                                            <html lang="tr">
                                                                                                            <head>
                                                                                                              <meta charset="UTF-8">
                                                                                                                <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- mobil uyum -->
                                                                                                                  <title>RootRa'ya Giriş Yap</title>
                                                                                                                    <style>
                                                                                                                        body {
                                                                                                                              display:flex;
                                                                                                                                    justify-content:center;
                                                                                                                                          align-items:center;
                                                                                                                                                height:100vh;
                                                                                                                                                      background:#111;
                                                                                                                                                            color:white;
                                                                                                                                                                  font-family:sans-serif;
                                                                                                                                                                        margin:0;
                                                                                                                                                                              padding:15px; /* telefonda kenara yapışmasın */
                                                                                                                                                                                  }
                                                                                                                                                                                      .login-box {
                                                                                                                                                                                            background:#222;
                                                                                                                                                                                                  padding:25px;
                                                                                                                                                                                                        border-radius:12px;
                                                                                                                                                                                                              box-shadow:0 0 20px rgba(0,0,0,0.5);
                                                                                                                                                                                                                    width:100%;
                                                                                                                                                                                                                          max-width:400px; /* pc’de 400px, telde %100 */
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                  h2 {
                                                                                                                                                                                                                                        text-align:center;
                                                                                                                                                                                                                                              margin-bottom:20px;
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                      input {
                                                                                                                                                                                                                                                            width:100%;
                                                                                                                                                                                                                                                                  padding:12px;
                                                                                                                                                                                                                                                                        margin:10px 0;
                                                                                                                                                                                                                                                                              border:none;
                                                                                                                                                                                                                                                                                    border-radius:6px;
                                                                                                                                                                                                                                                                                          font-size:16px;
                                                                                                                                                                                                                                                                                                box-sizing:border-box;
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                        button {
                                                                                                                                                                                                                                                                                                              width:100%;
                                                                                                                                                                                                                                                                                                                    padding:12px;
                                                                                                                                                                                                                                                                                                                          background:#007aff;
                                                                                                                                                                                                                                                                                                                                border:none;
                                                                                                                                                                                                                                                                                                                                      color:white;
                                                                                                                                                                                                                                                                                                                                            font-size:16px;
                                                                                                                                                                                                                                                                                                                                                  font-weight:bold;
                                                                                                                                                                                                                                                                                                                                                        border-radius:6px;
                                                                                                                                                                                                                                                                                                                                                              cursor:pointer;
                                                                                                                                                                                                                                                                                                                                                                    transition:0.2s;
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                            button:hover { background:#0051a8; }
                                                                                                                                                                                                                                                                                                                                                                                .error {
                                                                                                                                                                                                                                                                                                                                                                                      color:#ff4d4d;
                                                                                                                                                                                                                                                                                                                                                                                            font-size:14px;
                                                                                                                                                                                                                                                                                                                                                                                                  margin-bottom:10px;
                                                                                                                                                                                                                                                                                                                                                                                                        text-align:center;
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                p {
                                                                                                                                                                                                                                                                                                                                                                                                                      text-align:center;
                                                                                                                                                                                                                                                                                                                                                                                                                            margin-top:15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                  font-size:14px;
                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                          a { color:#0af; text-decoration:none; }
                                                                                                                                                                                                                                                                                                                                                                                                                                            </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </head>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <body>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="login-box">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>RootRa'ya Giriş Yap</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php if ($error) echo "<div class='error'>$error</div>"; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <form method="post">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="text" name="username" placeholder="Kullanıcı Adı" value="<?= htmlspecialchars($username) ?>" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input type="password" name="password" placeholder="Şifre" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit">Giriş</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>Hesabın yok mu? <a href="register.php">Kayıt Ol</a></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </html>