<?php
session_start();
include("db.php");

$error = "";
$success = "";
$username = "";
$ref_code = "";

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = trim($_POST['username']);
        $password = trim($_POST['password']);
            $ref_code = trim($_POST['ref_code']);

                // Referans kodu kontrolü
                    if ($ref_code !== "RootRaStr123456789") {
                            $error = "Geçersiz referans kodu!";
                                } else {
                                        // Kullanıcı adı daha önce var mı?
                                                $sql = "SELECT * FROM users WHERE username=? LIMIT 1";
                                                        $stmt = $conn->prepare($sql);
                                                                $stmt->bind_param("s", $username);
                                                                        $stmt->execute();
                                                                                $result = $stmt->get_result();

                                                                                        if ($result->num_rows > 0) {
                                                                                                    $error = "Bu kullanıcı adı zaten alınmış!";
                                                                                                            } else {
                                                                                                                        $hashed_pass = password_hash($password, PASSWORD_DEFAULT);
                                                                                                                                    $sql = "INSERT INTO users (username, password, ref_code) VALUES (?, ?, ?)";
                                                                                                                                                $stmt = $conn->prepare($sql);
                                                                                                                                                            $stmt->bind_param("sss", $username, $hashed_pass, $ref_code);
                                                                                                                                                                        if ($stmt->execute()) {
                                                                                                                                                                                        $success = "Kayıt başarılı! Giriş yapabilirsiniz.";
                                                                                                                                                                                                        $username = "";
                                                                                                                                                                                                                        $ref_code = "";
                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                    $error = "Kayıt başarısız oldu.";
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                            ?>
                                                                                                                                                                                                                                                                            <!DOCTYPE html>
                                                                                                                                                                                                                                                                            <html lang="tr">
                                                                                                                                                                                                                                                                            <head>
                                                                                                                                                                                                                                                                              <meta charset="UTF-8">
                                                                                                                                                                                                                                                                                <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Mobil uyum -->
                                                                                                                                                                                                                                                                                  <title>RootRa'ya Kayıt Ol</title>
                                                                                                                                                                                                                                                                                    <style>
                                                                                                                                                                                                                                                                                        body {
                                                                                                                                                                                                                                                                                              display:flex;justify-content:center;align-items:center;
                                                                                                                                                                                                                                                                                                    height:100vh;background:#111;color:white;font-family:sans-serif;
                                                                                                                                                                                                                                                                                                          margin:0;padding:15px;
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                  .register-box {
                                                                                                                                                                                                                                                                                                                        background:#222;padding:25px;border-radius:12px;
                                                                                                                                                                                                                                                                                                                              box-shadow:0 0 20px rgba(0,0,0,0.5);
                                                                                                                                                                                                                                                                                                                                    width:100%;max-width:400px;
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                            h2 { text-align:center;margin-bottom:20px; }
                                                                                                                                                                                                                                                                                                                                                input {
                                                                                                                                                                                                                                                                                                                                                      width:100%;padding:12px;margin:10px 0;
                                                                                                                                                                                                                                                                                                                                                            border:none;border-radius:6px;font-size:16px;
                                                                                                                                                                                                                                                                                                                                                                  box-sizing:border-box;
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                          button {
                                                                                                                                                                                                                                                                                                                                                                                width:100%;padding:12px;background:#28a745;
                                                                                                                                                                                                                                                                                                                                                                                      border:none;color:white;font-size:16px;
                                                                                                                                                                                                                                                                                                                                                                                            font-weight:bold;border-radius:6px;cursor:pointer;
                                                                                                                                                                                                                                                                                                                                                                                                  transition:0.2s;
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                          button:hover { background:#1e7e34; }
                                                                                                                                                                                                                                                                                                                                                                                                              .error { color:#ff4d4d;font-size:14px;margin-bottom:10px;text-align:center; }
                                                                                                                                                                                                                                                                                                                                                                                                                  .success { color:#00ff88;font-size:14px;margin-bottom:10px;text-align:center; }
                                                                                                                                                                                                                                                                                                                                                                                                                      p { text-align:center;margin-top:15px;font-size:14px; }
                                                                                                                                                                                                                                                                                                                                                                                                                          a { color:#0af;text-decoration:none; }
                                                                                                                                                                                                                                                                                                                                                                                                                            </style>
                                                                                                                                                                                                                                                                                                                                                                                                                            </head>
                                                                                                                                                                                                                                                                                                                                                                                                                            <body>
                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="register-box">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>RootRa'ya Kayıt Ol</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php if ($error) echo "<div class='error'>$error</div>"; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php if ($success) echo "<div class='success'>$success</div>"; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <form method="post">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="text" name="username" placeholder="Kullanıcı Adı" value="<?= htmlspecialchars($username) ?>" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="password" name="password" placeholder="Şifre" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="text" name="ref_code" placeholder="Referans Kodu" value="<?= htmlspecialchars($ref_code) ?>" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="submit">Kayıt Ol</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Zaten hesabın var mı? <a href="login.php">Giriş Yap</a></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>